### ISSUE TITLE
tablet (ipad) / safari:

"search jobs" button needs white space above/below it, similar to desktop.

### ISSUE THREAD

**Issue by computangit** [computangit/Extensis#169]
[https://www.bugherd.com/projects/177183/tasks/169](https://www.bugherd.com/projects/177183/tasks/169)

**Comment by computangit** [comment]
Hi @Kerry Gelhar ,

Updated.

Thanks,
M Aamir Aslam

**Comment by kerry** [comment]
@computangit Mr. Aslam,
Why are you mentioning me again and again? If I receive one more mention from you, I am going to report you.
