### ISSUE TITLE
check all icons to make sure they are not stretched.

### ISSUE THREAD

**Issue by computangit** [computangit/Extensis#77]
[https://www.bugherd.com/projects/177183/tasks/77](https://www.bugherd.com/projects/177183/tasks/77)

**Comment by computangit** [comment]
Hi @[Kerry Gelhar](273958) ,

We have grabbed these icons from sketch files as svg format and we used with the same size. If we need to change the icons please provide the high res icons in svg format. We will be happy to replace them.

Thanks,
M Aamir Aslam

**Comment by kerry** [comment]
Hi @computangit , 
I guess you are mentioning me @kerry on your issues. I am not at all related to this.

Thanks

**Comment by computangit** [comment]
#76 & #77 are referring to the same issue. see #76 for my comments. thank you! @[Web Support](253731)
